version: "3.7"

services:
    clickideia:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www

    # nginx
    nginx:
        container_name: servidor-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "5000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/

     # db mysql ${DB_DATABASE} //Busca do arquivo .env
    mysql:
        container_name: banco-mysql
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
            - mysql
        restart: always
        environment:
            - PMA_ARBITRARY=1
        ports:
            - 8000:80



#Doc. de utilizacao
# para acessar phpmyadmin no navegador: http://localhost:8000/ -  e a porta
# para acessar nginx(servidor) no navegador: http://localhost:5000/ - e a porta

#PHPMYADMIN info no file
# servidor: mysql
# user: root
# pass: root
